#!/bin/sh

STATUS=$(xrandr | grep "^DP-1 connected")

if echo "$STATUS" | grep -q "connected"; then
  if xrandr | grep "^DP-1 connected" | grep -q "[0-9]x[0-9]"; then
    xrandr --output DP-1 --off
  else
    xrandr --output DP-1 --auto --right-of eDP-1
  fi
fi
