#!/usr/bin/env bash

FOLDER=~/Pictures/wallpaper
SCRIPT=pywal16

set_wallpaper() {
    local img="$1"
    feh --bg-scale "$img"
    pywal16 &
}

menu () {
    if command -v nsxiv >/dev/null; then
        CHOICE=$(nsxiv -to "$FOLDER"/* | head -n 1)
    else
        CHOICE=$(echo -e "Random\n$(ls -v "$FOLDER")" | dmenu -c -l 15 -i -p "Wallpaper: ")
        CHOICE="$FOLDER/$CHOICE"
    fi

    case "$CHOICE" in
        Random)
            img=$(find "$FOLDER" -type f | shuf -n 1)
            set_wallpaper "$img"
            ;;
        "")
            exit 0
            ;;
        *)
            set_wallpaper "$CHOICE"
            ;;
    esac
}

case "$#" in
    0) menu ;;
    1) set_wallpaper "$1" ;;
    2) pywal16 &;;
    *) exit 0 ;;
esac
