vim.g.mapleader = " "
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set wrap!")
vim.cmd("set expandtab")
vim.cmd("set shiftwidth=2")
vim.cmd("set softtabstop=2")
vim.cmd("set mouse=")
vim.cmd("let g:lightline = {'colorscheme': 'tokyonight-night'}")
vim.cmd("set scrolloff=8")

-- KEY REMAPS --
vim.keymap.set("i", "jj", "<ESC>", { silent = true })
vim.keymap.set("v", "jj", "<ESC>", { silent = true })
vim.keymap.set("n", "<leader>q", ":q<CR>", { silent = true })
vim.keymap.set("n", "<leader>w", ":w<CR>", { silent = true })
vim.keymap.set("n", "yc", "\"+y", { silent = true })
vim.keymap.set("v", "yc", "\"+y", { silent = true })
vim.keymap.set("n", "yp", "\"+p", { silent = true })
vim.keymap.set("v", "yp", "\"+p", { silent = true })
vim.keymap.set("", "<up>", "<nop>", { noremap = true })
vim.keymap.set("", "<down>", "<nop>", { noremap = true })
vim.keymap.set("", "<left>", "<nop>", { noremap = true })
vim.keymap.set("", "<right>", "<nop>", { noremap = true })
